### ISSUE TITLE
Remove unimplemented internal functions.

### ISSUE THREAD

**Issue by noughtmare** [arrayfire/arrayfire-haskell#14]
Running `cabal test` fails because the linker can't find these functions:

In `Image.hsc`:
- `af_iterative_deconv`
- `af_iverse_deconv`

In `LAPACK.hsc`:
- `af_pinverse`

In `Signal.hsc`:
- `af_approx1_uniform`
- `af_approx2_uniform`

Should these functions be removed?

**Comment by dmjio** [comment]
@noughtmare can you confirm you're using `3.6.4`. If so, then yes I can make a PR to comment them out. They might have been implemented from building off of `master`.

**Comment by noughtmare** [comment]
@dmjio Yes, I'm using 3.6.4. Interestingly, there are some comments in the higher level *.hs files about this: https://github.com/arrayfire/arrayfire-haskell/blob/65bdf727def2bef77c47786585d19ba9050bd860/src/ArrayFire/LAPACK.hs#L198 and https://github.com/arrayfire/arrayfire-haskell/blob/65bdf727def2bef77c47786585d19ba9050bd860/src/ArrayFire/Signal.hs#L561

**Comment by dmjio** [comment]
`fftConvolve1` was commented out. I'll update the others as well. Thanks for looking into this.

**Comment by dmjio** [comment]
https://github.com/arrayfire/arrayfire-haskell/pull/17
